config/routes.rb
FinalProject::Application.routes.draw do
  resources :flags, only: [:new, :create]

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'users#index', as: 'dashboard'

  get 'landing_page' => 'home#landing_page'
  get 'desktop' => 'home#desktop', as: 'desktop'


  post 'update_location' => 'sparks#update_location', as: :update_location
  get "messages/:partner_id" => 'messages#show', as: :message
  get "messages/refresh/:partner_id" => 'messages#refresh', as: :message_refresh
  post "messages" => 'messages#create', as: :messages
  get "messages" => 'messages#index', as: :messages
  get "swipe_to_dash" => 'users#swipe_to_dash', as: :swipe_to_dash
  get "swipe_to_spark" => 'sparks#swipe_to_spark', as: :swipe_to_spark
  get "map" => 'sparks#map', as: "map"

  match 'users/auth/:service/callback' => 'services#create'
  resources :services, :only => [:index, :create, :destroy]
  resources :sparks, :only => [:show, :new, :create, :edit, :update, :destroy]
  get 'places' => 'sparks#places', as: 'places'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get ":page" => 'home#paginate'

  authenticated :user do
    root :to => "home#index"
  end

  root :to => "home#landing_page"


end

app/models/spark.rb
class Spark < ActiveRecord::Base
  attr_accessible :title, :content, :input_location, :latitude, :longitude, :user_id, :location_only

  validates_presence_of :latitude, :longitude
  validates_length_of :content, :maximum => 1000, :allow_blank => true

  belongs_to :user
  has_many :flags, as: :flaggable

  reverse_geocoded_by :latitude, :longitude

  def is_flagged_by_user?(user)
    x = false
    self.flags.each do |flag|
      if flag.flagger_id == user.id
        x = true
      end
    end
    x
  end

  def created_near(time)
    self.created_at.between?(time - 3.hours, time + 3.hours)
  end
end

app/controllers/sparks_controller.rb
class SparksController < ApplicationController
  def show
    @spark = Spark.find(params[:id])
  end

  def new
    @spark = Spark.new
       @nearby_sparks = current_user.relevant_sparks
        @spark = Spark.new
       # will_paginate is designed to work on models; this allows it to work on an array
       current_page = params[:page] || 1
       per_page = 20
       @nearby_sparks = WillPaginate::Collection.create(current_page, per_page, @nearby_sparks.length) do |pager|
         pager.replace @nearby_sparks[pager.offset, pager.per_page].to_a
       end
  end

  def create
    @spark = Spark.new(params[:spark])

    respond_to do |format|
      if @spark.save
        format.html { redirect_to root_path, notice: 'Spark has been sent! YAY!'}
        format.js
      else
        format.html { redirect_to new_spark_path, :alert => 'Spark failed. You must first allow your location to be shared.' }
        format.js
      end
    end
  end

  def update_location
    @spark = Spark.new(:latitude => params[:latitude], :longitude => params[:longitude], :location_only => true, :user_id => current_user.id)

    respond_to do |format|
      if @spark.save
        @nearby_sparks = current_user.relevant_sparks
        format.html { redirect_to root_path, notice: 'Spark has been sent! YAY!'}
        format.js
      else
        format.html { redirect_to new_spark_path, :alert => 'Spark failed. You must first allow your location to be shared.' }
        format.js
      end
    end

  end


  def places
    # @nearby_sparks = current_user.relevant_sparks
    @my_locations = current_user.places_ive_been
  end

  def edit
    @spark = Spark.find(params[:id])
    if @spark.user_id != current_user.id
      redirect_to spark_path(@spark), :alert => "You do not have access to edit that spark."
    end
  end

  def update
    @spark = Spark.find(params[:id])

    respond_to do |format|
      if @spark.update_attributes(params[:spark])
        format.html { redirect_to root_path, notice: 'Spark has successfully updated.'}
        format.js
      else
        format.html { redirect_to root_path, :alert => 'Spark update failed.' }
        format.js
      end
    end
  end

  def destroy
    @spark = Spark.find(params[:id])
    @spark.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def map
    # @my_locations = current_user.places_ive_been_for_map
    @nearby_sparks_for_map = current_user.relevant_sparks_for_map
  end

  def swipe_to_spark
    @spark = Spark.new
  end


end

app/helpers/sparks_helper.rb
module SparksHelper
end

app/views/sparks/_edit_partial.html.haml
#editspark.padding
  %section.bck.light.padding.text.center
    .row.text.book
      %h1 Edit this Spark
      %hr

      = form_for @spark, :method => "put", :remote => true do |f|
        = f.label :title
        = f.text_field :title, :id => "title", :placeholder => "I fell for you...."
        = f.label :input_location, "Location of Spark"
        = f.text_field :input_location, :id => "input_location", :placeholder => "The Hattery, SOMA, etc...."
        = f.label :content, "Spark Description"
        = f.text_area :content, :id => "content", :placeholder => "I almost tripped over my charger to hold the door for you...."
        = f.submit "Submit", :class => "button anchor alert"

app/views/sparks/_map.html.erb
<section class="bck light padding">
        <div class="row text center">
            <h3>Your Places</h3>
            <hr>


            <div id="mapbounds">
            <div id='map'></div>
        </div>
        </div>
    </section>

<script type='text/javascript'>
    L.mapbox.accessToken = 'pk.eyJ1IjoiZ2RvbWluZ3UiLCJhIjoieWNkSk1vUSJ9.n2JMI4LKoHvHqfF_bFJXGQ';
    var map = L.mapbox.map('map', 'mapbox.streets')
        // map.addLayer(L.tileLayer('http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg'));

    var markers = new L.MarkerClusterGroup();

    // The below is in case we ever want to add locations you have been/updated locations
    //
    // var addressPoints = <%= raw(@my_locations) %>

    // for (var i = 0; i < addressPoints.length; i++) {
    //     var a = addressPoints[i];
    //     var title = a[2] + "\n" + a[3];
    //     var marker = L.marker(new L.LatLng(a[0], a[1]), {
    //         icon: L.mapbox.marker.icon({'marker-symbol': 'post', 'marker-color': '0044FF'}),
    //         title: title
    //     });
    //     marker.bindPopup(title);
    //     markers.addLayer(marker);
    // }

    var sparkPoints = <%= raw(@nearby_sparks_for_map) %>

    for (var i = 0; i < sparkPoints.length; i++) {
        var a = sparkPoints[i];
        var title = '"' + a[2] + '"' + "\n" +  a[3];
        var marker = L.marker(new L.LatLng(a[0], a[1]), {
            icon: L.mapbox.marker.icon({'marker-symbol': 'post', 'marker-color': '5544AA'}),
            title: title,
            url: a[4]
        });

        // http://leafletjs.com/reference.html#popup
        var popupContent =  '<a target="_blank" class="popup" data-remote="true" href="/' + a[4] + '">' +
                            '   <p>' + title + '<p>' +
                            '</a>';

        marker.bindPopup(popupContent,{
            closeButton: true,
            maxWidth: 170
        });
        markers.addLayer(marker);
    }

    map.addLayer(markers);
    // zoom the map to fit the bounds of the markers:
    if (sparkPoints.length > 0){
        setTimeout(function(){map.fitBounds(markers.getBounds())}, 1000);
    }


</script>

app/views/sparks/_pin_dropped.html.haml
%h3.padding#profile_link
  Pin Dropped! Finish your Spark in your
  = link_to "Profile!", profile_path, :remote => true

app/views/sparks/_show_partial.html.haml
#sparkshow
  %section.bck.padding.light.text.center
    .row.text.book
      #flagged_spark
        - if @spark.is_flagged_by_user?(current_user)
          #already_flagged You have already flagged this spark

      %h2.mypadding= @spark.title
      %span.icon.heart
      %hr
      %h5
        = @spark.content

      %hr
      %h5
        This spark occurred at
      %h6.text.bold
        = @spark.input_location
      %h5
        = @spark.created_at.advance(:hours => -7).strftime('%B %e, %Y at %l:%M %p')

      %hr
      #sparkshowlinks
        - if @spark.user_id == current_user.id
          = link_to 'Edit this spark', edit_spark_path(@spark.id), :remote => true
          = link_to "Delete", spark_path(@spark), :data => { :confirm => "Are you sure?" }, :method => :delete
        - else
          = link_to 'Message this user', message_path(@spark.user_id), :remote => true
          = link_to('Flag this spark', '#', html_options = {id: 'flag_link'})
      %hr
        = form_for Flag.new, remote: true do |f|
          = f.label :reason, 'Reason for this flag:'
          = f.text_area :reason
          = f.hidden_field :flaggable_type, value: 'Spark'
          = f.hidden_field :flagged_id, value: @spark.id
          = f.submit "Flag this Spark", data: { confirm: "Are you sure? You will not be able to undo this action." }, :class => "button secondary"

app/views/sparks/_sparksnew.html.haml
/ Remember if you are going to update this page, also update the ajax partial
%section.bck.padding.light.text.center
  .row.text.padding.book
    %h1 Make a new Spark

    #geolocation_status.text.normal.bold
      / The following will be auto updated by the spark_location.js if coords are found.
      %p.bck.theme.text.white.bold NOTE: You must first "accept" the geolocation settings to post a spark

    %hr

    = form_for @spark, :method => "post" do |f|
      = f.label :title
      = f.text_field :title, :id => "title", :placeholder => "I fell for you...."
      = f.label :input_location, "Location of Spark"
      = f.text_field :input_location, :id => "input_location", :placeholder => "The Hattery, SOMA, etc...."
      = f.label :content, "Spark Description"
      .countdown
      = f.text_area :content, :id => "content", :placeholder => "I almost tripped over my charger to hold the door for you...."
      = f.hidden_field :user_id, :value => current_user.id
      = f.hidden_field :latitude,  :id => "lat"
      = f.hidden_field :longitude, :id => "lon"
      = f.submit "Submit", :class => "button anchor alert"

    #new_pin_div
      %h3.padding Or, drop a pin, and return later to complete your Spark!

      = form_for @spark, :method => "post", :remote => true, :html => {:id => 'new_pin'}  do |f|
        = f.hidden_field :user_id, :value => current_user.id
        = f.hidden_field :latitude,  :id => "lat2"
        = f.hidden_field :longitude, :id => "lon2"
        = f.submit "Drop a Pin", :class => "button anchor secondary"

app/views/sparks/create.js.erb
$('#new_pin_div').empty().html("<%= j render 'sparks/pin_dropped' %>")

app/views/sparks/delete.js.erb
alert('spark deleted!')

app/views/sparks/edit.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

new_spark.empty().removeAttr("style");
dashboard.empty().removeAttr("style");
homepage.empty().removeAttr("style");
other_pages.empty().removeAttr("style").html("<%= j render '/sparks/edit_partial' %>");

app/views/sparks/map.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

new_spark.empty().removeAttr("style");
dashboard.empty().removeAttr("style");
homepage.empty().removeAttr("style");
other_pages.empty().removeAttr("style").html("<%= j render '/sparks/map' %>");

app/views/sparks/new.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

other_pages.empty().removeAttr("style");
homepage.empty().removeAttr("style");
dashboard.empty().removeAttr("style");
new_spark.removeAttr("style").html("<%= j render '/sparks/sparksnew' %>")

new_spark.css('display', 'block');
new_spark.css("right", "0%");



homepage.html("<%= j render 'home/indexpartial' %>")
  $("#homepage").hide();
$("#homepage").css('left', '100%');
$("#homepage").css('display', 'none');



$(function() {
  var ask_for_geolocation;
  ask_for_geolocation = function() {
    var handleNoGeolocation, send_data;
    handleNoGeolocation = function(errorFlag) {
      if (errorFlag) {
        return console.log("Geolocation service failed.");
      } else {
        return console.log("Your browser doesn't support geolocation.");
      }
    };
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        window.latitude = position.coords.latitude;
        window.longitude = position.coords.longitude;
        return send_data();
      }, function() {
        return handleNoGeolocation(true);
      });
    } else {
      handleNoGeolocation(false);
    }
    return send_data = function() {
      $("#lat").val(latitude);
      $("#lon").val(longitude);
      $("#lat2").val(latitude);
      $("#lon2").val(longitude);
      return $("#geolocation_status").empty().append();
    };
  };
  if ($('#geolocation_status').length !== 0) {
    return ask_for_geolocation();
  }

});

var body = $('body');

function updateCountdown() {
    // 1000 is the max message length
    var remaining = 1000 - $('#content').val().length;
    jQuery('.countdown').html(remaining + ' characters remaining.');
}

if ($('#new_spark').length !== 0){
  updateCountdown();
  body.on('change', '#content', updateCountdown);
  body.on('keydown','#content', updateCountdown);
}

app/views/sparks/show.html.haml
#sparkshow
  %section.bck.padding.light.text.center
    .row.text.book
      #flagged_spark
        - if @spark.is_flagged_by_user?(current_user)
          #already_flagged You have already flagged this spark

      %h2.mypadding= @spark.title
      %span.icon.heart




      %hr
      %h5
        = @spark.content

      %hr
      %h5
        This spark occurred at
      %h6.text.bold
        = @spark.input_location
      %h5
        = @spark.created_at.advance(:hours => -7).strftime('%B %e, %Y at %l:%M %p')

      %hr
      #sparkshowlinks
        - if @spark.user_id == current_user.id
          = link_to 'Edit this spark', edit_spark_path(@spark.id)
          = link_to "Delete", spark_path(@spark), :data => { :confirm => "Are you sure?" }, :method => :delete
        - else
          = link_to 'Message this user', message_path(@spark.user_id), :remote => true

        = link_to('Flag this spark', '#', html_options = {id: 'flag_link'})
      %hr
        = form_for Flag.new, remote: true do |f|
          = f.label :reason, 'Reason for this flag:'
          = f.text_area :reason
          = f.hidden_field :flaggable_type, value: 'Spark'
          = f.hidden_field :flagged_id, value: @spark.id
          = f.submit "Flag this Spark", data: { confirm: "Are you sure? You will not be able to undo this action." }, :class => "button secondary"

app/views/sparks/show.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

new_spark.empty().removeAttr("style");
dashboard.empty().removeAttr("style");
homepage.empty().removeAttr("style");
other_pages.empty().removeAttr("style").html("<%= j render '/sparks/show_partial' %>");

app/views/sparks/swipe_to_spark.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

dashboard.empty().removeAttr("style");
other_pages.empty().removeAttr("style");

new_spark.removeAttr("style")
$(function(){
  if($("#new_spark_div").is(":empty")){
    $("#new_spark_div").html("<%= j render '/sparks/sparksnew' %>")
  }
})


var smoothtrans = function(){
  new_spark.css('display', 'block');
  homepage.css('position', 'absolute')
  homepage.css('width', '100%')
  homepage.animate({
    left:'100%',
    opacity: 1
  },{ duration: 500, queue: false});

  new_spark.animate({
    right: "0%",
    opacity: 1
  }, {duration: 500, queue: false});

}

smoothtrans();



$(function() {
  var ask_for_geolocation;
  ask_for_geolocation = function() {
    var handleNoGeolocation, send_data;
    handleNoGeolocation = function(errorFlag) {
      if (errorFlag) {
        return console.log("Geolocation service failed.");
      } else {
        return console.log("Your browser doesn't support geolocation.");
      }
    };
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        window.latitude = position.coords.latitude;
        window.longitude = position.coords.longitude;
        return send_data();
      }, function() {
        return handleNoGeolocation(true);
      });
    } else {
      handleNoGeolocation(false);
    }
    return send_data = function() {
      $("#lat").val(latitude);
      $("#lon").val(longitude);
      $("#lat2").val(latitude);
      $("#lon2").val(longitude);
      return $("#geolocation_status").empty().append();
    };
  };
  if ($('#geolocation_status').length !== 0) {
    return ask_for_geolocation();
  }

});

var body = $('body');

function updateCountdown() {
    // 1000 is the max message length
    var remaining = 1000 - $('#content').val().length;
    jQuery('.countdown').html(remaining + ' characters remaining.');
}

if ($('#new_spark').length !== 0){
  updateCountdown();
  body.on('change', '#content', updateCountdown);
  body.on('keydown','#content', updateCountdown);
}

app/views/sparks/update.js.erb
var new_spark = $("#new_spark_div")
var homepage = $("#homepage")
var dashboard = $("#dashboard")
var other_pages = $("#other_pages")
var mainwrapper = $("#mainwrapper")

new_spark.empty().removeAttr("style");
dashboard.empty().removeAttr("style");
homepage.empty().removeAttr("style");
other_pages.empty().removeAttr("style").html("<%= j render '/sparks/show_partial' %>");