config/routes.rb
FinalProject::Application.routes.draw do
  resources :flags, only: [:new, :create]

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'users#index', as: 'dashboard'

  get 'landing_page' => 'home#landing_page'
  get 'desktop' => 'home#desktop', as: 'desktop'


  post 'update_location' => 'sparks#update_location', as: :update_location
  get "messages/:partner_id" => 'messages#show', as: :message
  get "messages/refresh/:partner_id" => 'messages#refresh', as: :message_refresh
  post "messages" => 'messages#create', as: :messages
  get "messages" => 'messages#index', as: :messages
  get "swipe_to_dash" => 'users#swipe_to_dash', as: :swipe_to_dash
  get "swipe_to_spark" => 'sparks#swipe_to_spark', as: :swipe_to_spark
  get "map" => 'sparks#map', as: "map"

  match 'users/auth/:service/callback' => 'services#create'
  resources :services, :only => [:index, :create, :destroy]
  resources :sparks, :only => [:show, :new, :create, :edit, :update, :destroy]
  get 'places' => 'sparks#places', as: 'places'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get ":page" => 'home#paginate'

  authenticated :user do
    root :to => "home#index"
  end

  root :to => "home#landing_page"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smitten</title>
  <link href='http://fonts.googleapis.com/css?family=Coustard' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

  <!-- The following are for mapbox.js -->
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.css' rel='stylesheet' />
  <!-- The previous are for mapbox.js  -->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body id ="body">
  <% if !current_user.nil? %>
    <section class="bck alert" id ="nav">
      <div class="row text center">
        <nav data-tuktuk="menu" class="column_12 text center bold">
          <%= link_to new_spark_path, :remote => true, :id => "sparkbutton", :class => "left"  do %>
            <span class="icon heart">
          <% end %>
            <%= link_to root_path, :remote => true, :id => "homebutton" do %>
              <h3>Smitten</h3>
            <% end %>
            <%= link_to dashboard_path, :remote => true, :id => "dashbutton", :class => "right" do %>
              <span class="icon grid-large"></span>
            <% end %>
        </nav>
      </div>
    </section>
  <% end %>


    <div id="mainwrapper">
      <div id="homepage">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %></div>
      <div id="new_spark_div"></div>
      <div id="dashboard"></div>
      <div id="other_pages"></div>
    </div>


<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
</body>
</html>